### ISSUE TITLE
Schematic export crash

### ISSUE THREAD

**Issue by HakkaTjakka** [Zarbuz/FileToVox#21]
After getting missing .dll files installing some .net stuff:

D:\Downloads\FileToVox-v1.9.3>filetovox --i test.schematic --o hoppa.vox
[INFO] Specified input path: test.schematic
[INFO] Specified output path: hoppa.vox
[INFO] Specified increase size: 1
[INFO] Specified output path: D:\Downloads\FileToVox-v1.9.3\hoppa.vox
[LOG] Started to read config.txt for loading blocks colors
[INFO] Loaded blocks: 452
[LOG] Done.
System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at fNbt.NbtByteArray.ReadTag(NbtBinaryReader readStream)
   at fNbt.NbtCompound.ReadTag(NbtBinaryReader readStream)
   at fNbt.NbtFile.LoadFromStreamInternal(Stream stream, TagSelector tagSelector)
   at fNbt.NbtFile.LoadFromStream(Stream stream, NbtCompression compression, TagSelector selector)
   at fNbt.NbtFile.LoadFromFile(String fileName, NbtCompression compression, TagSelector selector)
   at fNbt.NbtFile..ctor(String fileName)
   at FileToVox.Converter.SchematicToSchematic.WriteSchematic() in E:\Documents\FileToVox\SchematicToVoxCore\Converter\SchematicToSchematic.cs:line 33
   at FileToVox.Program.SchematicToVox(AbstractToSchematic converter, String outputPath) in E:\Documents\FileToVox\SchematicToVoxCore\Program.cs:line 292
   at FileToVox.Program.ProcessFile() in E:\Documents\FileToVox\SchematicToVoxCore\Program.cs:line 245

**Comment by HakkaTjakka** [comment]
Other:
D:\Downloads\FileToVox-v1.9.3>filetovox --i hoppa.schematic --o hoppa.vox
[INFO] Specified input path: hoppa.schematic
[INFO] Specified output path: hoppa.vox
[INFO] Specified increase size: 1
[INFO] Specified output path: D:\Downloads\FileToVox-v1.9.3\hoppa.vox
[LOG] Started to read config.txt for loading blocks colors
[INFO] Loaded blocks: 452
[LOG] Done.
[LOG] Started to read all blocks of the schematic...
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at FileToVox.Converter.SchematicToSchematic.<>c__DisplayClass10_0.<GetBlocks>b__0(Int32 y) in E:\Documents\FileToVox\SchematicToVoxCore\Converter\SchematicToSchematic.cs:line 159
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at FileToVox.Converter.SchematicToSchematic.GetBlocks(RawSchematic rawSchematic) in E:\Documents\FileToVox\SchematicToVoxCore\Converter\SchematicToSchematic.cs:line 173
   at FileToVox.Converter.SchematicToSchematic.LoadSchematic(NbtFile nbtFile) in E:\Documents\FileToVox\SchematicToVoxCore\Converter\SchematicToSchematic.cs:line 78
   at FileToVox.Converter.SchematicToSchematic.WriteSchematic() in E:\Documents\FileToVox\SchematicToVoxCore\Converter\SchematicToSchematic.cs:line 34
   at FileToVox.Program.SchematicToVox(AbstractToSchematic converter, String outputPath) in E:\Documents\FileToVox\SchematicToVoxCore\Program.cs:line 292
   at FileToVox.Program.ProcessFile() in E:\Documents\FileToVox\SchematicToVoxCore\Program.cs:line 245
 ---> (Inner Exception #1) System.NullReferenceException: Object reference not set to an instance of an object.
   at FileToVox.Converter.SchematicToSchematic.<>c__DisplayClass10_0.<GetBlocks>b__0(Int32 y) in E:\Documents\FileToVox\SchematicToVoxCore\Converter\SchematicToSchematic.cs:line 159
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #2) System.NullReferenceException: Object reference not set to an instance of an object.
   at FileToVox.Converter.SchematicToSchematic.<>c__DisplayClass10_0.<GetBlocks>b__0(Int32 y) in E:\Documents\FileToVox\SchematicToVoxCore\Converter\SchematicToSchematic.cs:line 159
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #3) System.NullReferenceException: Object reference not set to an instance of an object.
   at FileToVox.Converter.SchematicToSchematic.<>c__DisplayClass10_0.<GetBlocks>b__0(Int32 y) in E:\Documents\FileToVox\SchematicToVoxCore\Converter\SchematicToSchematic.cs:line 159
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #4) System.NullReferenceException: Object reference not set to an instance of an object.
   at FileToVox.Converter.SchematicToSchematic.<>c__DisplayClass10_0.<GetBlocks>b__0(Int32 y) in E:\Documents\FileToVox\SchematicToVoxCore\Converter\SchematicToSchematic.cs:line 159
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

**Comment by Zarbuz** [comment]
Can you provide me your schematic which failed ? All my tests with schematic are done with Mineways.

**Comment by Zarbuz** [comment]
Ok after more investigation it seems that your are trying to import a new format of schematic which obviously seems to be not supported. Can you tell me from which software/tool this schematic is coming from ?
