### ISSUE TITLE
PLY to VOX Color Palette issue? libgdiplus installled but no luck

### ISSUE THREAD

**Issue by enzyme69** [Zarbuz/FileToVox#26]
I am getting result where the voxel color seems to have the palette, but they are not transferring color to each voxel. Very strange.

<img width="786" alt="Screen Shot 2021-02-01 at 12 08 23 pm" src="https://user-images.githubusercontent.com/3952687/106404253-5aff2d00-6486-11eb-817e-f511827c0059.png">

Original point cloud:
![IMG_F6175288794C-1](https://user-images.githubusercontent.com/3952687/106404328-8f72e900-6486-11eb-922e-e6fb03a01951.jpeg)

**Comment by enzyme69** [comment]
I wonder if you can try and convert to vox the original PLY below:
[rainbow 2.ply.zip](https://github.com/Zarbuz/FileToVox/files/5901305/rainbow.2.ply.zip)

**Comment by enzyme69** [comment]
```
192-168-1-110:FileToVox-v1 jimmygunawan$ dotnet FileToVox.dll -i /Users/jimmygunawan/Downloads/rainbow.ply -scale 70 -o rainbow
[INFO] Specified input path: /Users/jimmygunawan/Downloads/rainbow.ply
[INFO] Specified output path: rainbow
[INFO] Specified increase size: 70
[INFO] Specified output path: /Applications/FileToVox-v1/rainbow
[LOG] Start reading PLY data...
[LOG] Done.        
[LOG] Started to voxelize data...
[LOG] Done.        
System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'libgdiplus': The specified module could not be found.
   at System.Runtime.InteropServices.FunctionWrapper`1.get_Delegate()
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromScan0(Int32 width, Int32 height, Int32 stride, Int32 format, HandleRef scan0, IntPtr& bitmap)
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at FileToVox.Extensions.Quantization.CreateBitmapFromColors(List`1 blocks) in E:\Documents\FileToVox\SchematicToVoxCore\Extensions\Quantization.cs:line 50
   at FileToVox.Extensions.Quantization.ApplyQuantization(List`1 blocks, Int32 colorLimit) in E:\Documents\FileToVox\SchematicToVoxCore\Extensions\Quantization.cs:line 15
[INFO] Vox Width: 466
[INFO] Vox Length: 478
[INFO] Vox Height: 140
[LOG] Started to compute the first block for each region
[LOG] Done.        

```

**Comment by enzyme69** [comment]
I have tried installing libgdiplus but somewhat still no luck

Unable to load DLL 'libgdiplus': The specified module could not be found

**Comment by Zarbuz** [comment]
![image](https://user-images.githubusercontent.com/4965714/106433186-1d8fa500-6470-11eb-901d-3ec284602618.png)

The conversion works well if you have indeed the libdiplus library installed.

**Comment by enzyme69** [comment]
@Zarbuz Yes, I don't know what I did wrong because I brew that library and it's inside Cellar. Do I need to manually assign path or something?

**Comment by Zarbuz** [comment]
The official way to install libgdiplus is to use this command : `brew install mono-libgdiplus` for MacOS. 

Did you tried to relaunch your command prompt after the installation of libgdiplus ?

**Comment by enzyme69** [comment]
Yes I tried relaunching terminal multiple times.

<img width="1108" alt="Screen Shot 2021-02-01 at 7 42 44 pm" src="https://user-images.githubusercontent.com/3952687/106434638-efd54b00-64c5-11eb-94a1-d14b7010ef2d.png">


<img width="1282" alt="Screen Shot 2021-02-01 at 7 44 06 pm" src="https://user-images.githubusercontent.com/3952687/106434658-f5329580-64c5-11eb-97b8-18f24e89db07.png">


<img width="1183" alt="Screen Shot 2021-02-01 at 7 30 48 pm" src="https://user-images.githubusercontent.com/3952687/106434674-fcf23a00-64c5-11eb-9114-df96eb9ceb0a.png">

**Comment by enzyme69** [comment]
I found this:
https://gist.github.com/mtolly/384dbe51f4a78d6d2818

The mention of that nuget "runtime.osx.10.10-x64.CoreCompat.System.Drawing" etc, I also tried that but still no luck. I might be close and have to keep digging...

<img width="568" alt="Screen Shot 2021-02-01 at 7 47 56 pm" src="https://user-images.githubusercontent.com/3952687/106434988-62dec180-64c6-11eb-8930-4b645f634ccc.png">

**Comment by enzyme69** [comment]
I ended up creating new account on my MacOS, and it seems to work now. Same computer, different account. Maybe this one is pointing at the correct library. Weird... Thanks all!

```
Last login: Mon Feb  1 21:10:36 on console
Restored session: Mon  1 Feb 2021 21:02:56 AEDT
blendersushi@192-168-1-110 FileToVox-v1 % dotnet FileToVox.dll -i /Users/blendersushi/Downloads/piggu.ply -scale 70 -o piggu

[INFO] Specified input path: /Users/blendersushi/Downloads/piggu.ply
[INFO] Specified output path: piggu
[INFO] Specified increase size: 70
[INFO] Specified output path: /Users/blendersushi/Downloads/FileToVox-v1/piggu
[LOG] Start reading PLY data...
[LOG] Done.        
[LOG] Started to voxelize data...
[LOG] Done.        
[INFO] Vox Width: 593
[INFO] Vox Length: 753
[INFO] Vox Height: 266
[LOG] Started to compute the first block for each region
[LOG] Done.        
[INFO] Total blocks: 243297
[LOG] Started to write chunks ...
[########--]  85% \[LOG] Done.
[LOG] Check total blocks after conversion: 243297
[LOG] Done.
blendersushi@192-168-1-110 FileToVox-v1 % 

```

**Comment by enzyme69** [comment]
I think this is related. I am using iMac M1 and having the same issue quite annoying. I can't get the mono-libgdiplus running properly on this new account.

https://solrevdev.com/2020/12/04/dllnotfoundexception-unable-to-load-shared-library-libgdiplus-or-one-of-its-dependencies.html

**Comment by enzyme69** [comment]
Maybe somewhere along this line:
dotnet add package runtime.osx.10.10-x64.CoreCompat.System.Drawing

**Comment by enzyme69** [comment]
https://github.com/mono/libgdiplus/issues/696

**Comment by enzyme69** [comment]
If it's a matter of linking, I also have no idea how to search and link it:
https://github.com/dotnet/runtime/issues/34646
