### ISSUE TITLE
Problem with converting OBJ on mac os 10.13

### ISSUE THREAD

**Issue by Orkhan075** [Zarbuz/FileToVox#38]
Orkhans-MacBook-Pro:FileToVox-v1.12.6-osx orkhanhuseynov$ ./FileToVox --i /Users/orkhanhuseynov/Desktop/sphere.obj --o spherevoxel
[INFO] FileToVox v1.12.6.0
[INFO] Author: @Zarbuz. Contact : https://twitter.com/Zarbuz
[INFO] Specified input path: /Users/orkhanhuseynov/Desktop/sphere.obj
[INFO] Specified output path: spherevoxel
[INFO] Specified output path: /Users/orkhanhuseynov/Desktop/FileToVox-v1.12.6-osx/spherevoxel
[INFO] External program 'MeshSampler' needed! Check location of the program ...
[INFO] Check at: /Users/orkhanhuseynov/Desktop/FileToVox-v1.12.6-osx/MeshSampler/MeshSampler.exe
[INFO] MeshSampler/MeshSampler.exe found!
System.ComponentModel.Win32Exception (8): Exec format error
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at FileToVox.Converter.MeshToSchematic..ctor(String path, Single scale, Int32 colorLimit, Int32 segmentX, Int32 segmentY, Int32 subsample, Boolean skipCapture)
   at FileToVox.Program.GetConverter(String path)
   at FileToVox.Program.ProcessFile()

**Comment by Zarbuz** [comment]
MeshSampler isn't available for MacOS at the moment. 
However, you can convert you model to a point cloud through CloudCompare, you should watch my video tutorial : https://youtu.be/sg3z2GaMJzM
