### ISSUE TITLE
System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by crozynski** [Zarbuz/FileToVox#60]
When running FiletoVoxGUI v0.4 on Windows 11 for the first time I get the error:

**System.UnauthorizedAccessException: Access to the path 'D:\MagicaVoxel-0.99.6.4-win64\export\test.vox' is denied.**
at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode)
   at FileToVoxCore.Vox.VoxWriter.WriteModel(String absolutePath, List`1 palette, Schematic schematic, Rotation rotation)
   at FileToVox.Program.SchematicToVox(AbstractToSchematic converter)
   at FileToVox.Program.ProcessFile()

I'm a user with administrator privileges and the directories I'm trying to write to have Full Control set in Properties / Security.

None of my other apps have had trouble writing to the directories in question.

Any help much appreciated.

**Comment by ayliv** [comment]
Same problem here! It worked pretty well at first and out of nowhere, it began to act exactly the same. If someone could help us, it would be great! Thanks!
